version: '3.9'
services:
  mongo:
    container_name: mongo
    restart: "no"
    image: mongo:5.0.5
    command:
      - mongod
      # - --auth
      - --noscripting
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - twitter

  api:
    container_name: api
    restart: "always"
    build:
        context: ./api
        dockerfile: dockerfile
    env_file:
        - .env
    expose:
      - "0.0.0.0:3001:3001"
    depends_on:
      - "mongo"
    networks:
      - twitter

networks:
  twitter:
    driver: bridge

volumes:
  mongodata:


