FROM node:16.13.1-alpine3.14 As builder
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn config set disable-self-update-check true
RUN yarn install
COPY . .
RUN yarn build
RUN npm prune --production

FROM node:16.13.1-alpine3.14 as runner
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/node_modules/ ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3001
CMD yarn start:prod
